# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Crypto-App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Crypto-App

  target 'Crypto-AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Crypto-AppUITests' do
    # Pods for testing
  end

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'

end
